name: molsim
channels:
  - defaults
  - conda-forge
dependencies:
  - numpy
  - scipy
#  - python=3.7
  - ipython
  - ipykernel
  - numba
  - matplotlib
  - astropy
  - scikit-learn
  - jupyter
  - ipywidgets
  - xarray
  - dask
  - arviz
  - numexpr
  - tqdm
  - h5py
  - tabulate
  - emcee
  - loguru
  - lmfit
